name: arab_therapy_task
description:  Therapy Application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  freezed_annotation: ^2.0.3
  dio: ^4.0.6
  injectable: ^2.1.2
  get_it: ^7.6.0
  flutter_bloc: ^8.1.2
  dartz: ^0.10.1
  sizer: ^2.0.15
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  url_launcher: ^6.1.7
  flutter_svg: ^2.0.9



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.0.3+1
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0


flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/img/
    - assets/svg/
